### ISSUE TITLE
MX file won't load on non-Windows system

### ISSUE THREAD

**Issue by szhorvat** [arneeide/Chess#1]
The MX file won't load on non-Windows systems because the Windows-only `\` is used as the path separator.

I suggest you use `FileNameJoin` to build paths (not `<>`) and avoid using explicit separators.

Even better, instead of 

    packageDir = $AddOnsDirectory<>"\\Applications\\";

use 

    packageDir = DirectoryName[$InputFileName]

then 

    FileNameJoin[{packageDir, "pieceImages.mx"}]

This way the package does not need to be placed in a certain place to work.

**Comment by arneeide** [comment]
Absolutely! I apologise for this, the intension was initially to make this for my own pleasure. Then I realised that there may be others interested in the same topic. I have made a few changes in addition to your suggestion and will soon upload the corrected version. Thanks!

**Comment by arneeide** [comment]
Corrected. Thanks again.

**Comment by szhorvat** [comment]
Thanks for the fix :-)
